version: '3.8'

services:
  db:
    build: ./db
    environment:
      POSTGRES_DB: memes
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d memes"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data

  public_api:
    build: ./public_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/memes"
      MINIO_URL: "minio:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MINIO_BUCKET: "memes"

  media_service:
    build: ./media_service
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    depends_on:
      - minio
    environment:
      MINIO_URL: "minio:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MINIO_BUCKET: "memes"

  test:
    build: ./public_api
    command: ["pytest", "test_main.py"]
    depends_on:
      - db
      - minio
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/memes"
      MINIO_URL: "minio:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MINIO_BUCKET: "memes"

volumes:
  db_data:
  minio_data:
